/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

import java.awt.Color;

/**
 *
 * @author Aluno
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtTitle = new javax.swing.JLabel();
        panPrincipal = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        panServico = new javax.swing.JPanel();
        botServico = new javax.swing.JLabel();
        panCarro = new javax.swing.JPanel();
        botCarro = new javax.swing.JLabel();
        panCliente = new javax.swing.JPanel();
        botCliente = new javax.swing.JLabel();
        panUsuario = new javax.swing.JPanel();
        botUsuario = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        panCaixa = new javax.swing.JPanel();
        botCaixa = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtTitle.setBackground(new java.awt.Color(204, 204, 255));
        txtTitle.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        txtTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/concessionaria.png"))); // NOI18N
        txtTitle.setText("ASPEN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panPrincipal.setBackground(new java.awt.Color(153, 153, 255));
        panPrincipal.setLayout(new java.awt.GridLayout(4, 0));

        jPanel6.setLayout(new java.awt.GridLayout(1, 4));

        panServico.setBackground(new java.awt.Color(204, 204, 255));
        panServico.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        botServico.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        botServico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botServico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/servicos.png"))); // NOI18N
        botServico.setText("Gerenciar Serviços");
        botServico.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botServico.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botServico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botServicoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botServicoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panServicoLayout = new javax.swing.GroupLayout(panServico);
        panServico.setLayout(panServicoLayout);
        panServicoLayout.setHorizontalGroup(
            panServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botServico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panServicoLayout.setVerticalGroup(
            panServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botServico, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
        );

        jPanel6.add(panServico);

        panCarro.setBackground(new java.awt.Color(204, 204, 255));
        panCarro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        botCarro.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        botCarro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botCarro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/carro.png"))); // NOI18N
        botCarro.setText("Gerenciar Carros");
        botCarro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botCarro.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botCarro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botCarroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botCarroMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panCarroLayout = new javax.swing.GroupLayout(panCarro);
        panCarro.setLayout(panCarroLayout);
        panCarroLayout.setHorizontalGroup(
            panCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botCarro, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
        );
        panCarroLayout.setVerticalGroup(
            panCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botCarro, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
        );

        jPanel6.add(panCarro);

        panCliente.setBackground(new java.awt.Color(204, 204, 255));
        panCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        botCliente.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        botCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/cliente.png"))); // NOI18N
        botCliente.setText("Gerenciar Clientes");
        botCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botCliente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botClienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botClienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botClienteMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panClienteLayout = new javax.swing.GroupLayout(panCliente);
        panCliente.setLayout(panClienteLayout);
        panClienteLayout.setHorizontalGroup(
            panClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
        );
        panClienteLayout.setVerticalGroup(
            panClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
        );

        jPanel6.add(panCliente);

        panUsuario.setBackground(new java.awt.Color(204, 204, 255));
        panUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        botUsuario.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        botUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/usuario.png"))); // NOI18N
        botUsuario.setText("Gerenciar Usuário");
        botUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botUsuario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botUsuarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botUsuarioMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panUsuarioLayout = new javax.swing.GroupLayout(panUsuario);
        panUsuario.setLayout(panUsuarioLayout);
        panUsuarioLayout.setHorizontalGroup(
            panUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
        );
        panUsuarioLayout.setVerticalGroup(
            panUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
        );

        jPanel6.add(panUsuario);

        panPrincipal.add(jPanel6);

        jPanel7.setLayout(new java.awt.GridLayout(1, 4));

        panCaixa.setBackground(new java.awt.Color(204, 204, 255));
        panCaixa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        botCaixa.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        botCaixa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/caixa.png"))); // NOI18N
        botCaixa.setText("Gerenciar Caixa");
        botCaixa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botCaixa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botCaixa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botCaixaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botCaixaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botCaixaMousePressed(evt);
            }
        });

        javax.swing.GroupLayout panCaixaLayout = new javax.swing.GroupLayout(panCaixa);
        panCaixa.setLayout(panCaixaLayout);
        panCaixaLayout.setHorizontalGroup(
            panCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botCaixa, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
        );
        panCaixaLayout.setVerticalGroup(
            panCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botCaixa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel7.add(panCaixa);

        jPanel9.setBackground(new java.awt.Color(204, 204, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 406, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 124, Short.MAX_VALUE)
        );

        jPanel7.add(jPanel9);

        panPrincipal.add(jPanel7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botClienteMouseClicked
        setVisible(false);
        TelaManutencaoCliente tela = new TelaManutencaoCliente(this, true);
        tela.setVisible(true);
    }//GEN-LAST:event_botClienteMouseClicked

    private void botUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botUsuarioMouseClicked
        setVisible(false);
        TelaManutencaoUsuario tela = new TelaManutencaoUsuario(this, true);
        tela.setVisible(true);
    }//GEN-LAST:event_botUsuarioMouseClicked

    private void botUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botUsuarioMouseEntered
        panUsuario.setBackground(Color.white);
    }//GEN-LAST:event_botUsuarioMouseEntered

    private void botUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botUsuarioMouseExited
        panUsuario.setBackground(new Color(204,204,255));
    }//GEN-LAST:event_botUsuarioMouseExited

    private void botClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botClienteMouseEntered
        panCliente.setBackground(Color.white);
    }//GEN-LAST:event_botClienteMouseEntered

    private void botClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botClienteMouseExited
        panCliente.setBackground(new Color(204,204,255));
    }//GEN-LAST:event_botClienteMouseExited

    private void botCarroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botCarroMouseEntered
        panCarro.setBackground(Color.white);
    }//GEN-LAST:event_botCarroMouseEntered

    private void botCarroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botCarroMouseExited
        panCarro.setBackground(new Color(204,204,255));
    }//GEN-LAST:event_botCarroMouseExited

    private void botServicoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botServicoMouseEntered
        panServico.setBackground(Color.white);
    }//GEN-LAST:event_botServicoMouseEntered

    private void botServicoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botServicoMouseExited
       panServico.setBackground(new Color(204,204,255));
    }//GEN-LAST:event_botServicoMouseExited

    private void botCaixaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botCaixaMouseEntered
        panCaixa.setBackground(Color.white);
    }//GEN-LAST:event_botCaixaMouseEntered

    private void botCaixaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botCaixaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_botCaixaMousePressed

    private void botCaixaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botCaixaMouseExited
        panCaixa.setBackground(new Color(204,204,255));
    }//GEN-LAST:event_botCaixaMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel botCaixa;
    private javax.swing.JLabel botCarro;
    private javax.swing.JLabel botCliente;
    private javax.swing.JLabel botServico;
    private javax.swing.JLabel botUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel panCaixa;
    private javax.swing.JPanel panCarro;
    private javax.swing.JPanel panCliente;
    private javax.swing.JPanel panPrincipal;
    private javax.swing.JPanel panServico;
    private javax.swing.JPanel panUsuario;
    private javax.swing.JLabel txtTitle;
    // End of variables declaration//GEN-END:variables
}
